GlacioHack/xdem

DemUtils/coreg.py
tests/test_coreg.py

Added standalone `"deramp"` coregistration method and cleaned code.

Coreg variants

---

DemUtils/coreg.py
DemUtils/spatial_tools.py
README.md
tests/test_spatial_tools.py

Added DEM differencing function.
Changed the default coregistration method to "nuth_kaab" and improved code.
Added Examples section in the README.

DEM differencing, coreg.py changes and added Examples

---

DemUtils/coreg.py
tests/test_coreg.py

... or a path to either of the two.
Tests are included to verify that it works properly.

Coreg mask can now be Raster or Vector

---

xdem/dem.py

End of commits from the previous PR (Amaury's comments)
Added docstring for all functions in DEM class
Changed set_vref() priority to vref_grid argument
Checking for existence/correct naming of proj-data grid files through pyproj.datapath()
I was a bit busy for the early afternoon to start back on the coreg, will have more time tonight :) !

Docstring for DEM class + Default priority to grid + Checking proj-data files on disk

---

README.md

Updated the README to use the new `xdem` name.
Also added a short description of `dem.py`.

Updated README.md with new terminology

---

tests/test_dem.py
xdem/dem.py

See here for description: https://github.com/GlacioHack/GeoUtils/pull/118

Add DEM class init through same or parent class + tests

---

xdem/spatial_tools.py

Fix typo in previous commit

---

docs/source/comparison.rst

Added missing 'import numpy as np' statements to code examples

---

docs/source/coregistration.rst

There were many already outdated examples in the coregistration section. This fixes them.

Coregistration documentation fixes

---

tests/test_volume.py
xdem/volume.py

As seen by @adehecq  in #105, the function in volume.py did not return a dataframe similar to the input dataframe. This is fixed, and I've added some extra documentation.

Fix interpolate_hypsometric_bins

---

tests/test_dem.py

Updated test syntax to work with latest geoutils

---

.github/workflows/python-package.yml
README.md
environment.yml
setup.py
tests/test_ddem.py

Update readme and environment.yml to make installation easier with conda+pip

---

README.md

This is just to suggest the same as for GeoUtils.

Recommend testing in Readme

---

README.md

Badges are fun, badges look nice, here come more!
To see what it looks like: https://github.com/adehecq/xdem/tree/badges

Add more badges!

---

docs/source/conf.py
tests/test_coreg.py
tests/test_ddem.py
tests/test_dem.py
tests/test_demcollection.py
tests/test_docs.py
tests/test_filters.py
tests/test_spatial_tools.py
tests/test_spstats.py
tests/test_volume.py
xdem/coreg.py
xdem/ddem.py
xdem/dem.py
xdem/demcollection.py
xdem/filters.py
xdem/spatial_tools.py
xdem/spstats.py
xdem/volume.py

It's all in the title.
Resolves #153

Homogenize module description, remove per-script author contribution, add main author names to readthedocs

---

pyproject.toml
xdem/spstats.py
xdem/terrain.py

Solves #171. Doctests now need to pass in the CI.
@rhugonnet, you might want to have a look at one of the doctests in your recent PR. I had to change the return value!

Run doctests with pytest

---

xdem/examples.py

To create a parent directory with integrated exception handling
Brought up in #161 
Resolves #176

Use pathlib mkdir

---

HOW_TO_RELEASE.md

All in the title.
Also adds the incrementation of version number in "the hard way" following https://github.com/GlacioHack/geoutils/issues/269.
Ready to merge.

Add `HOW_TO_RELEASE` file

---

tests/test_misc.py

Following comment of @adehecq in GeoUtils:
https://github.com/GlacioHack/geoutils/pull/314#discussion_r975483816

Fix version check in `misc.test_deprecate`

---

.github/workflows/python-package.yml
.pre-commit-config.yaml

All in the title, same done in GeoUtils and KH-9 repo.

Fix `flake8` hook address in `pre-commit`

---

doc/source/conf.py

Went a bit fast and forgot to lint.

Linting of #351

---

.readthedocs.yaml

This is a one line PR with a minor change to readthedocs config file.
Solves #362.

Enable building the doc in offline formats

---

dev-environment.yml
tests/test_terrain.py

Skipping test and quick fix before version release.
Opened issues #376 and #377.

Fix `richdem` build issue and new warning in `terrain.py`

---

doc/source/conf.py

Report MySt-NB failures as error in Sphinx build

---

doc/source/intro_robuststats.md
examples/advanced/plot_standardization.py
examples/advanced/plot_variogram_estimation_modelling.py
xdem/spatialstats.py

Use NMAD consistently in examples and clarify link to Dowd's variogram in doc

---

.github/workflows/pre-commit.yml
.github/workflows/python-package.yml
.github/workflows/python-publish.yml

Solves #410.
I also took the liberty to update other actions that have new versions.

Update CI action versions.

---

tests/test_ddem.py
xdem/ddem.py

Fix `dDEM.nodata` setting on instantiation 

---

HOW_TO_RELEASE.md
doc/source/how_to_install.md
tests/test_coreg/test_base.py

Based on @adehecq's recent comments, ongoing.

Minor a posteriori fixes on recent PRs

---

dev-environment.yml
environment.yml
requirements.txt

Unfix scipy version with `curve_fit` bug now fixed in `1.11.4` 

---

.github/dependabot.yml
.pre-commit-config.yaml

Mirrors https://github.com/GlacioHack/geoutils/pull/476

Add dependabot and pre-commit CI for automatic versioning updates

---

.github/scripts/generate_pip_deps_from_conda.py
requirements.txt

Mirrors https://github.com/GlacioHack/geoutils/pull/512

Remove `setuptools` and `setuptools_scm` from requirements.txt

---

doc/source/vertical_ref.md
tests/test_dem.py
xdem/dem.py

Make `DEM.to_vcrs()` inplace by default

---

tests/test_coreg/test_biascorr.py

Add random seed for point cloud subsampling in `test_biascorr`

---

tests/test_coreg/test_base.py

Set random seed in `to_pointcloud` of pipeline point-raster test

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pip-checks.yml
setup.cfg

Fix pip tests since Python 3.13 release

---

doc/source/accuracy_precision.md

Add ASPRS reference to page on "Accuracy and precision"

---

tests/test_coreg/test_workflows.py
xdem/coreg/workflows.py

Update and unskip test for `dem_coregistration` workflow

---

setup.cfg

Update version number to `0.1.0`

---

doc/source/about_xdem.md
doc/source/authors.md
doc/source/funding.md
doc/source/mission.md

Had forgotten to fix the last warnings.

Minor fixes to documentation

---

.github/workflows/pip-checks.yml
.github/workflows/python-tests.yml

Temporary fix to intermittent setup-miniconda issues in CI

---

dev-environment.yml
environment.yml
requirements.txt
tests/test_dem.py

Fix minor changes impacting tests, and bump dependency.

Update with GeoUtils 0.1.14

---

dev-environment.yml
environment.yml
requirements.txt
xdem/coreg/base.py

- Update GeoUtils version in `envionment.yml`, `dev-environment.yml`, `requirements.txt`.
- Modify access path to a GeoUtils function in `coreg.base`

Update with GeoUtils 0.1.16

---

.github/workflows/pip-checks.yml
setup.cfg

Mirrors https://github.com/GlacioHack/geoutils/pull/687

Use automatic `packages.find` listing to avoid forgetting `setuptools` modules

---

.gitignore

Add example file created during doc build to `.gitignore`

---

doc/source/code/robust_mean_std.py
doc/source/code/spatialstats_heterosc_slope.py
doc/source/robust_estimators.md
doc/source/uncertainty.md
examples/advanced/plot_standardization.py
examples/advanced/plot_variogram_estimation_modelling.py
xdem/coreg/base.py
xdem/spatialstats.py

I'm waiting for the CI to see the warnings of pytest. 
I think the 400 warnings come from the install

Finish replacing `nmad` by version in GeoUtils

---

dev-environment.yml
environment.yml
requirements.txt

Update for GeoUtils 0.1.17 (and GeoPandas 1.1)

---

dev-environment.yml
environment.yml
requirements.txt
setup.cfg
xdem/dem.py
xdem/fit.py
xdem/spatialstats.py

Also fixing some issues with the lazy import of `scikit-learn`.

Make SciKit-GStat dependency optional
