GlacioHack/xdem

.gitignore
environment.yml
setup.py
tests/test_coreg.py
xdem/coreg.py
xdem/examples.py

We had two options for where to put the examples directory:
`xdem/examples/`
or
`examples/`
currently, both are used!
This PR makes only the latter be used.

Move examples to one place: a separate examples directory + ICP coreg improvements

---

tests/test_spatial_tools.py
xdem/spatial_tools.py

In GDAL, only the operators "first" and "last" can be applied when merging (mosaicing) rasters. This often creates quite ugly seams, and may hide good data (a NaN in one raster can replace a value in another). Additionally, when dealing with multiple DEMs, one might want to calculate statistics such as the median, standard deviation (or anything else) within each cell.
An example:
```python
dem_west = gu.georaster.Raster("path/to/dem1")
dem_east = gu.georaster.Raster("path/to/dem2")
merged_dem = xdem.spatial_tools.merge_rasters([dem_west, dem_east])
```
or:
```python
list_of_many_dems = [...]
standard_deviation = xdem.spatial_tools.merge_rasters(list_of_many_dems, merge_algorithm=np.nanstd)
nmad = xdem.spatial_tools.merge_rasters(list_of_many_dems, merge_algorithm=xdem.spatial_tools.nmad) …
```

Function to merge rasters using any callable (mean, median, sum etc)

---

environment.yml
tests/test_spstats.py
xdem/__init__.py
xdem/spstats.py

Tools for:
- Variogram wrapper: unfortunately the scikit-gstat object is, at this stage, a bit useless (can't fit multi-range, some exception are unstable). So I move empirical variograms to a simple pandas.Dataframe: variance, lag, count.
- Multi-range estimation: need specific binning (for now I will test the "kmeans" option added in skgstat, but we might have to resort to our own binning, although skgstat doesn't allow for customized binning so it will be annoying), with multiple runs (to assess the stability/std of the empirical variogram) that can be run in parallel using multiprocessing (typically 10,000 samples will take several minutes, it can go up pretty fast)
- Integration of variogram/covariance functions over a spatial support: circular integration (spatially continuous …

Spatial statistics: empirical variogram estimation, numerical variogram integration into volume errors

---

setup.py
xdem/coreg.py

`pip install git+https://github.com/GlacioHack/xdem.git` is now enough to install xdem! See #48 for what was previously needed on a clean install.
```bash
❯ conda create -n clean_env python ipython
❯ conda activate clean_env
❯ pip install git+https://github.com/GlacioHack/xdem.git
❯ ipython
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import geoutils
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
In [2]: import xdem
```
I guess the geoutils error is because of GDAL... It's always GDAL!
I will mark this as a draft, …

Fix 'pip install' to install all dependencies

---

docs/source/comparison.rst
docs/source/conf.py
docs/source/coregistration.rst
tests/test_ddem.py
xdem/ddem.py
xdem/demcollection.py
xdem/volume.py

I've added local and hypsometric interpolation for the `dDEM` and `DEMCollection` classes. They are functional right now, but will be given some improvements. Hence, I will create a draft PR.
The regional approach works as follows:
1. Mask out the glacier areas using a provided mask or glacier outlines
2. Calculate a regional elevation change gradient from the masked dDEM.
3. Apply the gradient model to the reference DEM to get an "idealized dDEM"
4. Calculate the difference between the idealized dDEM and the actual dDEM, and linearly interpolate it.
5. Correct the idealized dDEM with the difference in 4) to get the final interpolated dDEM
The local approach does approximately the same thing, but it calculates it for each `Vector.ds` row separately. So point nr 2-5 are done iteratively …

Local and regional hypsometric dDEM interpolation

---

docs/source/coregistration.rst
setup.py
tests/test_coreg.py
xdem/coreg.py

The entire coregistration structure has been revisited in this PR, with modularity and simplicity in focus.
All approaches are now sublasses of the `Coreg` class, which is heavily inspired by the structure employed in `scikit-learn`. Chaining coregistration functions is as simple as adding them using the "+" operator, or by explicitly constructing a `CoregPipeline` from a `list[Coreg]`.
Right now, I've added a lot of code, and have marked the old stuff with `DeprecationWarning`s. 
Later (or in this PR), I'll remove all of the old code.
In the following examples, I will use the same data, defined below:
```python
xdem.examples.download_longyearbyen_examples(overwrite=False)
reference_dem = xdem.DEM(xdem.examples.FILEPATHS["longyearbyen_ref_dem"])
dem_to_be_aligned = …
```

Modular `coreg.py` revision

---

xdem/ddem.py
xdem/volume.py

These are some fix I had to make to run the local hypsometric interpolation on a ddem with very large gaps, for example with outlines falling completely outside of valid range.
@erikmannerfelt please check if what I've made makes sense and we can discuss how to better account for such cases.

Make hyspometric interpolation methods more gap-friendly

---

xdem/examples.py

As you may have noticed, testing and doc-building takes a very long time because data are quite inefficiently downloaded from the source.
On my computer, this download takes about 3 minutes. When using GitHub Actions, it takes around 13 minutes on their servers! 
I have created a new repo: https://github.com/erikmannerfelt/xdem-data, which could replace the way we fetch data. There, scripts exist for fetching the data from source, but the modified data are in the repo itself. Therefore, `xdem` can get the data by just fetching the latest `xdem-data` tarball and extracting whatever is needed.
Downloading the Longyearbyen data takes 2.23 s on my computer. That's a 81x performance increase!
Above just making docs, CI and general testing easier, this would ensure that testing data are not …

Use `xdem-data` repo for example data

---

tests/test_coreg.py
xdem/coreg.py

Sometimes when working with nadir photogrammetric reconstructions, dDEMs can show elevation-dependent differences due to a miscalculated focal length. Obviously, that is a sign that one should probably redo the photogrammetry! If that is not possible, however, this correction may be used instead.
This function estimates a linear or polynomial model with altitude and corrects for it. Example usage:
```python
dem = xdem.DEM(examples.FILEPATHS["longyearbyen_ref_dem"])
factor = 1.2   # Simulated scale offset
scaled_dem = dem.data * factor
zcorr = xdem.coreg.ZScaleCorr(degree=1)
zcorr.fit(dem.data, scaled_dem)
unscaled_dem = xcorr.apply(dem.data) 
diff = (dem.data - unscaled_dem).filled(np.nan)
assert np.abs(np.nanmedian(diff)) < 0.01
```
This passes, as shown by the tests.
As per #78, maybe …

Add elevation scale correction `Coreg` approach.

---

docs/source/coregistration.rst

Docs failed to build in 470ad6a, hehe...
I have successfully built this PR in my fork, so it works now: https://readthedocs.org/projects/xdem-erikm/builds/13507007/
Maybe we should add an action soon to make sure our PRs don't mess up the docs?

Fix typo which made docs fail

---

.github/workflows/python-package.yml
.github/workflows/python-publish.yml
README.md
docs/source/comparison.rst
environment.yml
tests/test_coreg.py
tests/test_dem.py
tests/test_spatial_tools.py
tests/test_spstats.py
tests/test_volume.py
xdem/coreg.py
xdem/spstats.py

I've made some corrections to make the tests work better than before. There are still some issues, and 2/37 still fail for me. @rhugonnet, I was hoping you could tell me what's up? It's the `DEM.set_vref()` test that fails with:
```
ValueError: Grid not found in /home/erik/.local/share/conda/xdem/lib/python3.8/site-packages/pyproj/proj_dir/share/proj: check if proj-data is installed via conda-forge, the pyproj.datadir, and that you are using a grid available at https://github.com/OSGeo/PROJ-data
```
when trying to set the vref to `'is_lmi_Icegeoid_ISN93.tif'` at:
https://github.com/GlacioHack/xdem/blob/64f348b6318aaa6313707772f99426294bfa6e38/tests/test_dem.py#L129
and a `Proj error` at:
https://github.com/GlacioHack/xdem/blob/64f348b6318aaa6313707772f99426294bfa6e38/tests/test_dem.py#L148 …

Improve test suite to pass and add CI

---

dev-requirements.txt
docs/source/code/comparison.py
docs/source/code/comparison_plot_local_hypsometric_interpolation.py
docs/source/code/comparison_plot_regional_hypsometric_interpolation.py
docs/source/code/comparison_plot_spatial_interpolation.py
docs/source/code/comparison_print_cumulative_dh.py
docs/source/code/coregistration.py
docs/source/code/coregistration_plot_nuth_kaab.py
docs/source/comparison.rst
docs/source/conf.py
docs/source/coregistration.rst
tests/test_docs.py
xdem/examples.py
xdem/spstats.py

This was a hard one, including environment variables and all kinds of weird errors!
There were quite many warnings before when building the documentation. I've made sure that all of them have been fixed.
I've added tests for all example scripts (I'll get more to that in a second) and for building the documentation. Now, theoretically, ReadTheDocs should always build if the build check on GitHub passes. Makes for easier maintainability in the long term, as a PR that passes the build check should be compatible with ReadTheDocs (right now, builds might pass but then the documentation fails to build!).
Finally, since we already have had trouble with outdated examples, all example code is now in `docs/source/code/*.py`. This has many advantages:
1. Linters and formatters can locally help with …

Improve documentation, add documentation testing, and make all examples into scripts.

---

tests/test_spatial_tools.py
xdem/spatial_tools.py

Add new optional features to `xdem.spatial_tools.merge_rasters`:
- **include_ref**: set to False will not include reference in the merging
- **use_ref_bounds**: set to True will use ref's bounds rather than max bounds
Fix bug:
- merge_bounding_boxes was checking that bounds were a multiple of resolution, whereas only the extent should be a multiple. @erikmannerfelt you might want to check that
Update the tests accordingly.

Improve merge_rasters

---

tests/test_spatial_tools.py
xdem/spatial_tools.py

This was harder than I thought!
Initially inspired by [earthpy](https://earthpy.readthedocs.io/en/latest/_modules/earthpy/spatial.html) (since we wanted to avoid more dependencies), I set on to remake their function in the style of xdem. Turns out, however, that their hillshade function is not accurate! 
As noted by @adehecq  in #102, the input DEM of `earthpy.spatial.hillshade()` needed to be divided by an (at the time) arbitrary value to get the right z-scale. Turns out, hillshades need the resolution to generate properly! Makes sense in hindsight, considering that the `np.gradient` just  gets the pixel differences, so the horizontal scale is needed for a proper z-scale.
So here we have it: our very own hillshade function. I've made sure that it works well with nans/ masked_arrays as …

Add hillshade function.

---

tests/test_coreg.py
xdem/coreg.py
xdem/ddem.py
xdem/spatial_tools.py
xdem/volume.py

We are getting quite many issues, and many of them are relatively small. I therefore decided to just tackle a few in one PR!
* Solves #114:  A `Coreg.centroid()` method now exists which fetches the centroid if it exists.
* Solves #113: A more descriptive `ValueError` replaces the cv2 error.
* Solves #112: All `Coreg` approaches now raise an error if only nans are encountered.
* Tackles #110: The better "check if matrix is only vertical" suggestion by @adehecq is implemented.
* Tackles #89: `spatial_tools.get_array_and_mask()` now converts to (height, width) and raises an error if it can't be converted.
* Solves #76: A `Coreg.residuals()` method is added. Then a `Coreg.error()`method is added for preset error measures made form the residuals.
* Solves #66: A check now exists for the …

Consistency fixes, and added error/residual methods to Coreg class.

---

xdem/volume.py

Several error arise when running the several hypsometric interpolation methods, when there are too few valid pixels.
This PR tries to solve those issues.

Fix hypsometric interpolation for large gaps

---

environment.yml
setup.py

The default branch name in GeoUtils has been changed from `master` to `main`, so the download URLs have to be changed accordingly.

Change URLs in accordance with geoutils master->main rename.

---

.github/workflows/python-package.yml
.github/workflows/python-publish.yml
.readthedocs.yml
README.md
dev-environment.yml
docs/source/conf.py
environment.yml
setup.py
tests/test_coreg.py
tests/test_docs.py

* All dependencies are now on conda-forge!
* Removed `richdem` from the `environment.yml` as it is an optional dependency
* Removed `pdal` as it is no longer in use.
* Set minimum python version to 3.7 (because of type annotations)
* Ran `black` on `setup.py` since formatting was all over the place.
* The `build` workflow no longer uses pip to install dependencies.
* Prepared `build` workflow to build on Windows and MacOS (didn't enable it yet).
* Updated `README.md` accordingly.
In 0c3c06f, I also added:
* Documentation versioning now dynamically follows the setup.py version (it was hardcoded before..)
* Added manual dispatch to PyPi publishing workflow (see https://github.com/GlacioHack/GeoUtils/pull/192)
* Bumped version to `v0.0.3` (bugfixes on all fronts)
In aa3485f, I added a …

Update dependencies and version

---

tests/test_filters.py
xdem/__init__.py
xdem/filters.py

I've added several filters to the newly created filters module. For now it features:
- several implementations of the Gaussian filters (openCV, scipy)
- all filters are insensitive to NaNs, i.e. the filtered value ignore NaNs
- an outlier filtering based on a threshold distance to the Gaussian filtered raster
There are some differences between opencv's and scipy's Gaussian filters that I don't understand, in particular regarding the kernel size. So for now, the kernel size is left to default, which seem to yield similar results for both implementations. This is not a big deal as most users won't care about the kernel size, only on the sigma value.
For example:
```
V1 = scipy.ndimage.gaussian_filter(V, sigma=10, truncate=4)
V2 = cv.GaussianBlur(V, (40, 40), sigmaX=10, …
```

Add a filter module and several filters.

---

docs/source/code/coregistration_plot_nuth_kaab.py
tests/test_dem.py
xdem/ddem.py
xdem/dem.py

As mentioned in https://github.com/GlacioHack/GeoUtils/issues/211, a warning was triggered by `SatelliteImage` (and thus `DEM`) upon instantiation. This made some tests fail, as they have a "no warning" policy.
This PR fixes that, together with two warnings that have been bugging me for a while:
1. dDEM.interpolate("local_hypsometric") triggered an interpolation warning (which is supposed to be okay)
2. A matplotlib deprecation warning was triggered for a documentation code snippet, which I've fixed.

Fix failing test and add handlers for warnings.

---

tests/test_spstats.py
xdem/spstats.py

Scipy base function on which I rely: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.binned_statistic_dd.html#scipy.stats.binned_statistic_dd
After some searching, the pure pandas solutions seemed a bit hard to extend in N-dimensions: https://stackoverflow.com/questions/60340107/pandas-dataframe-bin-on-multiple-columns-get-statistics-on-another-column
Suggestions of other implementations are welcome. Originally, my own functions were quite simply based on multiple `for` loops, so lots of room for improvement here  :exploding_head: (those can actually run quite fast, especially when using numba).
```python
from xdem.spatial_tools import nmad
list_df_1d, list_df_2d, list_df_nd = xdem.spstats.nd_binning_scipy(dh=diff.data.flatten(), …
```

Add N-dimensional binning function (for biases, non-stationarity quantification etc..)

---

.gitignore
tests/test_spstats.py
xdem/spatial_tools.py
xdem/spstats.py

Added ring/circular shape masking to subsample rasters.
This will extremely useful to better estimate empirical variograms from the raster samples. Because we generally have millions of samples in a raster, we can't calculate the millions^{squared} pairwise differences. Sampling 10,000 points is already quite a long calculation (~1min). If we subsample within rings of different radius, we limit the samples to similar pairwise distances, thus improving the empirical estimation with less unused samples.
TODO: write the parent function to subsample with the ring method, iteratively, for different radius sizes.

Improve sampling for variogram estimation: circular and ring sampling + tests

---

tests/test_spatial_tools.py
xdem/spatial_tools.py

As mentioned in PR #135, a shared subsampling function would be useful.
**Done:**
- created the function
- added tests
**To do:**
- add tests with option 'return_indices"
- replace with this function where needed

Add a function for subsampling functionality

---

.github/workflows/python-package.yml
tests/test_coreg.py
tests/test_docs.py
tests/test_spatial_tools.py
xdem/coreg.py
xdem/misc.py
xdem/spatial_tools.py

Solves #142.
In many cases, biases are not systematic throughout the DEM, so a nonlinear correction is required. This new class takes an arbitrary Coreg class and makes it nonlinear!
The class takes two required arguments; the `Coreg` object to apply non-lienarly and the amount of `subdivisions` to calculate it within. In short, what it does is:
1. Subdivide the DEM in N (`=subdivison`) equally sized chunks.
2. For each chunk, run the coregistration separately, and save the results.
1. Take all the coregistration results and describe them as  X/Y/Z shifts in the middle of the grid. These shifts are then spatially interpolated to generate three offset fields.
2. Apply the Z shifts as a simple `dem - shift` correction
3. Apply the X/Y shifts using `skimage.transform.warp`
Below is an …

Add support for nonlinear coregistration

---

.gitignore
docs/source/code/comparison.py
docs/source/code/comparison_plot_local_hypsometric_interpolation.py
docs/source/code/comparison_plot_regional_hypsometric_interpolation.py
docs/source/code/comparison_plot_spatial_interpolation.py
docs/source/code/coregistration.py
docs/source/code/coregistration_plot_nuth_kaab.py
tests/test_coreg.py
tests/test_ddem.py
tests/test_dem.py
tests/test_demcollection.py
tests/test_filters.py
tests/test_spatial_tools.py
tests/test_spstats.py
tests/test_volume.py
xdem/examples.py

Added `process_coregistered_example` to `xdem/examples.py` that works similarly as `download_longyearbyen_examples`.
To differentiate the two when loading data from `examples`, I have renamed `FILEPATHS` into `FILEPATHS_DATA` and added a `FILEPATHS_PROCESSED`.
Now one can load the dDEM example through: `examples.FILEPATHS_PROCESSED['longyearbyen_ddem']`. I have refactored previous usages of `FILEPATHS` into `FILEPATHS_DATA`.
@erikmannerfelt I see most of your test cases for volume/ddem and plot scripts in the documentation simply use the difference between the non-aligned Longyearbyen rasters (rather than doing a N&K like I did in spatial_stats). Should we change those to using the dDEM data now that it is available, or keep them as is?

Store ddem example to minimize test/doc computing times

---

.gitignore
dev-environment.yml
dev-requirements.txt
docs/Makefile
docs/source/_templates/module.rst
docs/source/api.rst
docs/source/code/comparison.py
docs/source/code/comparison_print_cumulative_dh.py
docs/source/comparison.rst
docs/source/conf.py
docs/source/coregistration.rst
docs/source/index.rst
docs/source/tutorials.rst
examples/README.rst
examples/plot_blockwise_coreg.py
examples/plot_dem_subtraction.py
examples/plot_demcollection.py
examples/plot_icp_coregistration.py
examples/plot_norm_regional_hypso.py
examples/plot_nuth_kaab.py
xdem/__init__.py
xdem/coreg.py
xdem/examples.py

The example gallery seems to be working!
Now, an example in the `examples/` directory will show up in the `Example gallery`, and will link to the API if a function from xdem is used. It will also link to the documentation of `geoutils`, `numpy` and `matplotlib` (more can be added).
There are only two weird things:
- Things defined in the `__init__` does not really work (at least now; I'm sure it's fixable). Therefore, `xdem.DEM` refers to `gu.Raster` (since it can't find the definition of `xdem.DEM`). EDIT: This is now fixed!
- Each example has to be prepended with `plot_` in order to actually execute. This is according to https://github.com/sphinx-gallery/sphinx-gallery, and might be possible to circumvent. Still, I think it's a nice way to know which functions will run and which will …

Add example gallery

---

tests/test_spstats.py
xdem/spstats.py

Return a N-D interpolant function for binned explanatory variables.
Very much like np.interp1d but in N-D.
```python
df = xdem.spstats.nd_binning(values=diff.data.flatten(),list_var=[slope.flatten(),ref.data.flatten()],list_var_names=['slope','elevation'])
fun = robust_interp_nd_binning(df, ['slope','elevation'], statistic = nmad)
```
And you get a function that can return an interpolated value for any point (slope, elevation):
```
fun((5,1000))
Out[100]: array(2.42234615)
```
```
fun((15,1000))
Out[107]: array(4.61452136)
```
Here the NMAD is **~2 m** at 5° slope, 1000 m elevation and **~4 m** 15° slope, 1000 m elevation.
If you run this on the arrays of the explanatory variables, you can get your error map directly:
```python
err_dh = fun((slope.data,elevation.data))
```
Here the …

Add N-dimensional linear interpolation

---

tests/test_coreg.py
xdem/coreg.py

Solves #167.
I'm 97% sure I got the typing right. With the upcoming pre-commit PR, however, it can be validated better.

Make 'Coreg.fit' return 'self' for one-liner coregistration.

---

tests/test_volume.py
xdem/volume.py

The lowermost half bin of the glacier was not filled because of the midpoint-centered approach; Only the midpoints of the bins were evaluated, so the lower half of the lowermost bin was out of the interpolation range!
Adding `scipy.interpolate.interp1d(..., fill_value="extrapolate")` fixes this issue, so the lower half of the lowermost bin correctly uses the model for the lowermost bin, without introducing NaNs.
I've also added a test for nans to make sure this won't happen again.

Fix gap bug in `xdem.volume.norm_regional_hypsometric_interpolation`

---

docs/source/code/coregistration.py
tests/test_coreg.py
xdem/coreg.py

Solves #174.
See the issue for the new syntax!

Allow `Raster`s as inputs for `Coreg.fit()` and `Coreg.apply()`

---

README.md
docs/source/code/comparison.py
docs/source/code/comparison_plot_local_hypsometric_interpolation.py
docs/source/code/comparison_plot_regional_hypsometric_interpolation.py
docs/source/code/comparison_plot_spatial_interpolation.py
docs/source/comparison.rst
tests/test_ddem.py
tests/test_misc.py
tests/test_spatial_tools.py
xdem/demcollection.py
xdem/misc.py
xdem/spatial_tools.py

Closes #163.
All uses of `xdem.spatial_tools.subtract_rasters()` are now gone.
I've added a `xdem.misc.deprecate()` function with associated tests. It triggers a deprecation warning up to the version where it is supposed to be removed, whereby it will raise a ValueError. This means that if the repo is still using the deprecated function by then, it won't pass CI!

Deprecate `subtract_rasters`

---

.github/workflows/python-package.yml
docs/source/code/coregistration.py
tests/test_coreg.py
tests/test_docs.py
tests/test_filters.py
tests/test_spstats.py
xdem/spstats.py

Similar to my recent https://github.com/GlacioHack/GeoUtils/pull/222.
- bec7d29: The pytest CI log doesn't show 171 PASSED lines anymore!
- de84d32: Hid divide by zero warnings in `xdem.spstats.create_ring_mask()`. @rhugonnet  is that okay?
- 22c2830: Replaced all instances of `Raster.reproject(...)` to `Raster.reproject(..., silent=True)` in tests.

Fix testing warnings and improve CI testing output

---

tests/test_coreg.py
xdem/coreg.py

Closes #185.
Completely empty blocks are now skipped, and are not considered for the success percentage.
Also, a few warnings may occur before coreg approaches fail, so these are now caught and are by default not shown. For debug purposes, it can be shown by enabling the `warn_failures` attribute to `True` (can also be set as an argument to the `__init__()` method), whereby each failure and warning will be shown as warnings.

Exclude empty blocks in BlockwiseCoreg and handle warnings.

---

tests/test_terrain.py
xdem/dem.py
xdem/terrain.py

Tackles #178 
Now, this works:
```python
import xdem
dem = xdem.DEM(xdem.examples.get_path("longyearbyen_ref_dem"))
slope = xdem.terrain.slope(dem)  # This is a Raster since a RasterType was given as an argument.
slope.save(...)
```

Allow `Raster`s as arguments -> return types for terrain attributes

---

tests/test_coreg.py
xdem/coreg.py

Closes #189.
The blocks that were empty are now correctly skipped.
Also, I found that there were `inf`s in the stats! That is because the  `Coreg.residuals()` for some reason calculated an incorrect mask sometimes. I fixed that as well, so all of the statistics are finite.
These two issues are now fixed and correctly tested, so they should not reoccur.

Fix BlockwiseCoreg.stats() KeyError and improved tests.

---

tests/test_coreg.py
xdem/coreg.py
xdem/spatial_tools.py

Fixes #195 .
Changes:
- `warp_dem()` now has mask dilation by default.
- `get_array_and_mask()` takes and properly respects Rasters now (it was used with rasters before, but the mask was not respected).
- -9999 values in `warp_dem()` were replaced by np.nan
- Added a warning catcher in `apply_matrix()` (due to skimage + numpy deprecation warning)
- Improved test to validate that the above changes fixes the problem.
Something that is not tested automatically but was tested manually was the example by @adehecq in #195 in `examples/plot_blockwise_coreg.py`. As seen in the screenshot in #195, these fixes solve that problem.

Fix erroneous masks for Coreg classes

---

README.md
xdem/coreg.py
xdem/misc.py

Resolves #199
- Added a description of the solution to circumvent the `dlopen` issue in the **README**: based on https://github.com/scikit-learn/scikit-learn/issues/14485#issuecomment-761735034, with additional conditions for `numpy` to function properly
- Added loop for optional `cv2` imports that were missing in `coreg.py` and `misc.py`
- Moved `cv2` imports before xdem to avoid `opencv` TLS errors: https://github.com/tensorflow/models/issues/523
- Performed tests to check that `xdem` runs normally with environments solved by `conda`/`mamba`, all seems OK now.

Fix import errors, add solution for TLS issue on older systems

---

xdem/coreg.py

Deramping was not correcting tilts properly.
Now I can see my jitter quite clearly! 
Still need to deal with that one :sweat_smile:  
We need more tests, and more plotting functionalities to check our outputs! They are quite complex spatially, so just relying on some calculations through `pytest` routines is probably not enough (at least for their initial setup)

Fix Deramp

---

tests/test_coreg.py

Closes #211.
I don't know what you're smoking, @rhugonnet, but this works fine on my end! Was it CI or locally that it failed for you? For me, both pass.

Re-enable blockwise test

---

tests/test_coreg.py
xdem/coreg.py

Tackles several issues in Coreg methods with large gaps:
- issues #225 and #239, that are related: NaNs or nodata value that spread during resampling are not properly masked in certain cases
- partially solves issue #232: Coreg apply method tend to spread NaNs/gaps a lot when calling `apply_matrix`, especially with iterative pipelines. This PR makes the argument `dilate_mask` optional to turn this off, if needed.

Improve coreg methods with NaNs

---

tests/test_spatialstats.py
xdem/coreg.py

This is a fix to #237.
During coreg.apply, a resampling is needed. When NaNs exist in the input DEMs, the NaNs also propagate and must be handled carefully. Currently, such resampling is done at 3 different places, and NaNs are not always caught properly.
This PR tries to fix this issue.
I also fixed a small issue in BlockwiseCoreg. Errors during fitting were caught, but not during apply.

Fix issue with NaNs masks in Coreg methods

---

xdem/volume.py

`volume.calculate_hypsometry_area` raises an `AssertionError` when `ddem_bins` contains gaps/NaNs. This should not be the case when `timeframe` is set to "reference", as the ddem_bins values are not used.
Fixed this.

Fix issue in volume.calculate_hypsometry_area when ddem_bins contain NaNs

---

xdem/spatialstats.py

Before the PR, the functions `plot_1d_binning`, `plot_2d_binning` and `plot_vgm` would create a new figure by default (with ax=None). With ax set to an existing ax, the figure would actually occupy the whole figure and disregard subplots.
With this update, the figure only occupy the space for the provided Axes instance.

Update spatialstats.py plot functions to work with provided ax

---

dev-environment.yml
examples/README.rst

To avoid all hell breaking loose from https://github.com/GlacioHack/GeoUtils/pull/265, but also for long-term stability with releases.
Resolves #268

Force geoutils to 0.0.7

---

.github/workflows/python-package.yml
dev-environment.yml
dev-requirements.txt
environment.yml
tests/test_coreg.py
tests/test_dem.py
tests/test_examples.py
xdem/coreg.py
xdem/dem.py
xdem/examples.py
xdem/spatialstats.py
xdem/terrain.py

Because of the [MemoryFile PR](https://github.com/GlacioHack/GeoUtils/pull/265) in geoutils, several attributes of Raster objects do not exist. Fix bugs that arise with that change. Things important to keep in mind:
- the rasterio DatasetReader initially accessed with `self.ds` was removed
- the method `self._get_rio_attrs` was removed
- the method `self._update` was removed
Fixed several issues, but I still have a few that fail locally:

Fix bugs following geoutils update

---

.github/workflows/python-package.yml
dev-environment.yml
environment.yml
examples/advanced/plot_heterosc_estimation_modelling.py
tests/test_coreg.py
tests/test_spatialstats.py
xdem/coreg.py
xdem/demcollection.py
xdem/examples.py
xdem/terrain.py

Updating a couple tests that used syntax only supported by the previous `__array_interface__` or raised `UserWarning` due to the new `data.setter` of `Raster`.
Will make CI pass once https://github.com/GlacioHack/geoutils/pull/302 is merged.

Fix tests with GeoUtils `data.setter` and `__array_interface__` update

---

xdem/misc.py

Use `packaging.Version` for version check in our `deprecate` decorator
Should have realized this was also needed in #307

Fix `deprecate` version check

---

xdem/filters.py

Make opencv import optional

---

docs/source/quick_start.rst
tests/test_spatialstats.py
xdem/examples.py

This PR fixes a bug in the function `process_coregistered_examples` of `examples.py` that made the `ddem` processing run every time the file was called with `xdem.example.get_path("longyearbyen_ddem")`. This should save us some time in testing and building documentation! :smile:
Additionally, it makes the variables `FILEPATHS_DATA` and `FILEPATHS_PROCESSED` not accessible to users (adding `_` in front), and create the `xdem.examples.available` variable that list keys of both dictionaries that can be called with `xdem.examples.get_path()`, for consistency with GeoUtils https://github.com/GlacioHack/geoutils/pull/284.

Fix loading of processed examples in `examples.py`

---

.pre-commit-config.yaml
dev-environment.yml
dev-requirements.txt
environment.yml
examples/advanced/plot_blockwise_coreg.py
tests/test_coreg.py

An update from GeoUtils is required after #329, this PR prepares that by pulling the latest GeoUtils directly
And fixing some remaining bugs that didn't make it through in the other PR (docs, Windows).
One tricky problem introduced in the tests of #329, the `NamedTemporaryFile` has permissions issues on Windows (see https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file). Details:
> Whether the name can be used to open the file a second time, 
> while the named temporary file is still open, varies across platforms 
> **(it can be so used on Unix; it cannot on Windows NT or later)**.
After some tweaking, I fixed it using the `mode` and `delete` arguments of, trick added to the Wiki: https://github.com/GlacioHack/xdem/wiki/Stuck-on-a-mysterious-error-dur …

Fix xDEM with a new GeoUtils release

---

tests/test_dem.py
xdem/coreg.py
xdem/dem.py

Edit a few lines of the DEM class in xdem/dem.py, from
```
[86] # self.nbands can be None when data is not loaded through the Raster class
[87] if self.nbands is not None and self.nbands > 1:
[88]     raise ValueError("DEM rasters should be composed of one band only")
```
to 
```
[86] # self.indexes can be None when data is not loaded through the Raster class
[87] if self.indexes is not None and len(self.indexes) > 1:
[88]     raise ValueError("DEM rasters should be composed of one band only")
```
so that it fixed #339
EDIT from @rhugonnet:
Resolves #338 as well

Edit bands into indexes of DEM class

---

README.md
dev-environment.yml
docs/source/code/spatialstats.py
docs/source/code/spatialstats_heterosc_slope.py
environment.yml
examples/advanced/plot_heterosc_estimation_modelling.py
examples/basic/plot_dem_subtraction.py
tests/test_coreg.py
tests/test_ddem.py
tests/test_dem.py
tests/test_demcollection.py
tests/test_examples.py
tests/test_filters.py
tests/test_misc.py
tests/test_spatialstats.py
tests/test_terrain.py
tests/test_volume.py
xdem/coreg.py
xdem/ddem.py
xdem/dem.py
xdem/demcollection.py
xdem/examples.py
xdem/fit.py
xdem/misc.py
xdem/spatialstats.py
xdem/terrain.py
xdem/volume.py

To fix all issues that arose with https://github.com/GlacioHack/geoutils/pull/360 (including https://github.com/GlacioHack/geoutils/pull/351).
Resolves #342 
Might resolve #323, as #186 only tested errors in `BlockwiseCoreg.fit()` and not in `BlockwiseCoreg.apply()`
This PR only fixes what is in _xdem/_ and _tests/_, what is in _doc/_ will be done in #303 to avoid a merging nightmare.

Update with new GeoUtils (casting single-band to 2D, implicit loading, new module names)

---

doc/source/comparison.md
doc/source/conf.py
doc/source/coregistration.md
doc/source/spatialstats.md
doc/source/terrain.md

Redundant as those are now always displayed on the right side with `sphinx-book-theme`

Remove local table of contents in documentation 

---

.github/workflows/python-package.yml

See #353 for the rationale.
For once, it seems the fix was rather simple! But maybe the test suite fails for other reasons now.. Oh well, you can see that the exact syntax works in [variete](https://github.com/erikmannerfelt/variete/blob/main/.github/workflows/python-test.yml)
Closing #353

Fix GitHub Actions mamba caching

---

.coveragerc

Mirroring what was done in GeoUtils

Add `coveragerc` to ignore specific lines when estimating test coverage

---

tests/test_spatialstats.py

Opening an issue, there's probably a better way of testing this.

Remove `spatialstats` test based on `time` that randomly fails

---

.github/workflows/python-package.yml
dev-environment.yml
doc/source/conf.py

This PR fixes the inheritance diagrams rendering in the doc (that was shown as text).
Inheritance diagrams require `graphviz` to build. However, `mamba` has trouble updating the base `environment.yml` with `graphviz` in the CI (that runs into two steps: base environment + update with dev packages), because some image-processing package dependencies are similar.
To fix this, this PR explicitly adds `graphviz` when building the base `environment.yml` **only in the CI**.
All other scripts building from `dev-environment.yml` are functioning fine (readthedocs, developper install).
Resolves #359

Fix inheritance diagram rendering in documentation

---

.readthedocs.yaml

Fix typo in #363 (cannot be tested by CI), during build on Readthedocs:
> Problem in your project's configuration. Invalid "formats": expected one of (htmlzip, pdf, epub), got hmtlzip

Fix typo in `.readthedocs.yaml`

---

xdem/__init__.py

Resolves #347
Also the occasion to reset `latest` so that the xDEM documentation can build properly (worked on the doc of my branch, but on the main a random conda error stopped the build).

Fix package name in `xdem.__init__`

---

tests/test_biascorr.py
tests/test_spatialstats.py
xdem/spatialstats.py

Resolves #380 
The extrapolation is always done using "nearest", and interpolation is "linear" by default.
The workflow is a bit complex in order to deal with nodata in the grid, see comments in the code.
Added tests to ensure all works as intended.

Extrapolate using nearest neighbour in `interp_nd_binning`

---

dev-environment.yml
environment.yml
xdem/spatialstats.py

Resolves #393 
Should already be fixed in `scikit-gstat`: https://github.com/mmaelicke/scikit-gstat/issues/146
(`@njit` is equivalent to `@jit(nopython=True)`)
Opened #396

Silence numba warning for `@jit`

---

dev-environment.yml
environment.yml
xdem/coreg/affine.py

To simply the base environment, see #154

Make `noisyopt` an optional dependency

---

dev-environment.yml
environment.yml
setup.py

Forgot `pip` cannot be called from `conda build`, so versions would be inconsistent between PyPI and conda.
Reverting back `scikit-gstat` to `conda-forge`, the warnings (#395) will go away by themselves when its `1.0.11` release is made on `conda-forge`.
Additionally, still trying to figure out the circular import issue in `xdem-feedstock`...
Resolves #396

Only use `conda-forge` channel in environment

---

dev-environment.yml
environment.yml
xdem/coreg/base.py
xdem/coreg/pipelines.py

Update typing with GeoUtils `0.0.13`

---

README.md

In the end of the README, it states to push a feature branch to `geoutils:main` which is obviously wrong.

Update README.md to point to xdem instead of geoutils

---

tests/test_coreg.py
xdem/coreg/affine.py
xdem/coreg/base.py

My first PR in quite some time!
Two things have been done in this PR; re-implementing my PR (https://github.com/liuh886/xdem_snow/pull/7) to the fork that was #346, and solving some small issues that I've found along the way.
The first part is arguably the most important because the fit_pts functions of NuthKaab and GradientDescending have been at risk of being half a pixel off since #346 was merged! The tests introduced in the PR did not actually check for the fit_pts result on points, but only on rasters converted to points in a predefined manner. My PR (https://github.com/liuh886/xdem_snow/pull/7) that fixed this was unfortunately lost along the way in #346...  Anyway, here it is again, which fixes and tests the fit_pts half-pixel problem. The reason for the issue was that sampling was …

Multiple coreg `fit_pts` fixes.

---

setup.cfg

To fix a `conda-forge` error similar than https://github.com/GlacioHack/xdem/issues/394
Triggered by the changes in #429
Mirrors https://github.com/GlacioHack/geoutils/pull/404

Declare `xdem.coreg` module explicitly for `conda-forge`

---

.github/workflows/python-package.yml
CONTRIBUTING.md
dev-environment.yml
environment.yml
setup.cfg

Mirrors https://github.com/GlacioHack/geoutils/pull/406

Add support for Python `3.11` and remove `3.8`

---

tests/test_spatialstats.py
xdem/spatialstats.py

- Resolves #380,
- Adds ability to save plots of variograms and 1d/2d binning
- Adds ability in fit_sum_model_variogram() to pass a value for maxfev to curve_fit: this can sometimes help for some convergence problems
EDIT by @rhugonnet:
- Also adds support for using plot of 1d/2d binning with a `pd.Dataframe` containing `pd.Interval` written as strings.

Definitive fix of negative uncertainties from linear extrapolation

---

tests/test_coreg/test_affine.py
tests/test_coreg/test_base.py
xdem/coreg/base.py

This PR fixes a bug in `CoregPipeline` that made all fits erroneous (using the original `tba_dem` instead of the updated one).
This was only 4 characters, but not easy to find.

Fix bug in `CoregPipeline.fit()`

---

dev-environment.yml

Fixes the wrong rendering of the documentation since the pydate-sphinx-theme 0.14 by forcing 0.13 (see issue https://github.com/executablebooks/sphinx-book-theme/issues/761).
We should be able to update soon, `sphinx-book-theme` is catching up with a pre-release: https://github.com/executablebooks/sphinx-book-theme/releases.
Opened #452

Fix documentation rendering due to Pydata theme update

---

.github/workflows/python-publish.yml
.github/workflows/python-tests.yml
pyproject.toml
requirements.txt

Fixes `pip install xdem` for an empty environment (which currently fails), adds a test to check this always works, and updates action names
Mirrors https://github.com/GlacioHack/geoutils/pull/419, https://github.com/GlacioHack/geoutils/pull/420, https://github.com/GlacioHack/geoutils/pull/421 and https://github.com/GlacioHack/geoutils/pull/422

Fix PyPI publish, add tests and update action names

---

setup.cfg

Currently `pip install xdem` can fail on Python 3.12 because some dependencies (`numba`, notably) don't support it. And does so during publish.
We pin the version between 3.9 and 3.11 to ensure the PyPI publish always works.

Pin max Python version for `setuptools`

---

.github/workflows/python-publish.yml
setup.cfg

Only pin in PyPI publish workflow, leave version open in `setup.cfg` to still allow install on Python 3.12 (at user's own risk).

Pin max Python version for PyPI publish

---

tests/test_misc.py
xdem/misc.py

Mirrors https://github.com/GlacioHack/geoutils/pull/429

Fix `test_deprecate` to work with `setuptools_scm` versions

---

dev-environment.yml
environment.yml
requirements.txt

Mirrors https://github.com/GlacioHack/geoutils/pull/462
Resolves #452

Pin max major versions of dependencies for future compatibility

---

doc/source/biascorr.md
doc/source/coregistration.md

Tiny PR to fix a broken link in the documentation. 
Seems to have been a typo in a link to a paper that meant the doi lookup service responded with an error.

Fix link in coregistration.md

---

tests/test_terrain.py
xdem/terrain.py

This PR specifies that the argument `resolution` is optional in terrain functions, moves it down to the end of the list, and adds a note on aspect independence from resolution.
Tests were adjusted to all pass the `resolution` argument instead of relying on it as second positional.
Resolves #490

Clarify `resolution` in terrain docstrings

---

examples/advanced/plot_standardization.py
examples/advanced/plot_variogram_estimation_modelling.py

It was just that the number of samples were too low, easy fix!
Resolves https://github.com/GlacioHack/xdem/issues/445

Increase sample size of empirical variograms in advanced examples for clearer plots

---

examples/advanced/plot_slope_methods.py
examples/advanced/plot_variogram_estimation_modelling.py
examples/basic/plot_dem_subtraction.py
examples/basic/plot_icp_coregistration.py

Replaced old `print()` statements on DEMs with `info()` and homogenized the way plotting is done by always calling `Raster.plot()` when possible. Plus a couple text changes.
Will do more in a separate PR!
Resolves #286 
Resolves #374

Minor improvements to gallery examples

---

.github/workflows/python-tests.yml
tests/test_coreg/test_biascorr.py
xdem/fit.py

Ongoing...
Resolves #519 
Resolves #521

Fix CI errors due to basinhopping algorithm and coverage 

---

doc/source/coregistration.md
tests/test_coreg/test_affine.py
tests/test_coreg/test_base.py
tests/test_coreg/test_biascorr.py
xdem/coreg/affine.py
xdem/coreg/base.py
xdem/coreg/biascorr.py
xdem/examples.py

This PR makes the `.meta` attribute a public property of `Coreg`, and makes the attribute names consistent.
In particular:
- `"offset_east_px"` is now `"shift_x"`, and is in georeferenced units (instead of pixels) which allows to remove the `"resolution"` key in the metadata,
- `"offset_north_px"` is now `"shift_y"`,
- `"vshift"` is now `"shift_z"`,
Others are renamed to be consistent with `BiasCorr`.
Will be documented in #502!

Make coregistration metadata consistent and public

---

.gitignore
xdem/examples.py

Stemmed in #525 
Following https://github.com/GlacioHack/xdem-data/pull/1

Update link to `xdem-data` to use COGs example files

---

tests/test_coreg/test_base.py
tests/test_fit.py
xdem/coreg/base.py

Add `Coreg.fit_and_apply()` to run everything in one step

---

tests/test_coreg/test_base.py

Fix `CoregPipeline` tests subsampling by passing non-init Coreg objects

---

tests/test_coreg/test_affine.py
xdem/coreg/affine.py
xdem/coreg/base.py

This PR fixes and homogenizes the sign of translation parameters in coregistrations, and adds consistent tests mirrored from `test_biascorr` to ensure that affine coregistrations behave as intended for all types of input (raster-raster, raster-point, and point-raster).
In short: the new tests introduce synthetic shifts, then check that estimated coregistration shifts are exactly the same as those introduced within 1% (10% for ICP), and that applying the coregistration then corrects more than 99% of the variance in the initial elevation difference (95% for ICP). This ensures that the direction of coregistration is the right one, and that there is no other errors introduced in the process.
Before #530, the `_apply_rst` of different method such as `NuthKaab` and `ICP` relied on different …

Homogenize sign of translation coregistration and add affine tests

---

dev-environment.yml
environment.yml
requirements.txt
tests/test_coreg/test_affine.py
tests/test_coreg/test_base.py
xdem/coreg/__init__.py
xdem/coreg/affine.py
xdem/coreg/base.py

This PR performs the renaming and generalization as discussed in #231
@liuh886 @erikmannerfelt I indeed found a fairly big difference in performance between `scipy.optimize.minimize()` and `noisyopt.minimizeCompass()`. For SciPy, the "Nelder-Mead" method examplified by @sgascoin in #231 performed best of all, but it still had some trouble consistently correcting an artificial shift introduced in our Longyearbyen example data at different shift magnitudes and subsample sizes (even when passing bounds and various tolerances), while `minimizeCompass` performed OK on all cases. So between the default `minimize()` and `minimizeCompass()`, there is a big difference in performance, but the difference is much smaller between  `minimize(method="Nelder-Mead")` and `minimizeCompass`.
So, to avoid …

Refactor `GradientDescending` to `DhMinimize` with generic inputs

---

doc/source/logging.md
examples/basic/logging_configuration.py
examples/basic/temp.tif.aux.xml
tests/test_coreg/test_affine.py
tests/test_coreg/test_base.py
tests/test_coreg/test_biascorr.py
tests/test_demcollection.py
tests/test_doc.py
tests/test_spatialstats.py
xdem/coreg/affine.py
xdem/coreg/base.py
xdem/coreg/biascorr.py
xdem/coreg/workflows.py
xdem/fit.py
xdem/spatialstats.py
xdem/volume.py

Resolves #565 
This pull request addresses the transition from using `print()`statements to the Python `logging` module. The update improves flexibility for managing output messages.
- Replaced all occurences of `print` with appropriate logging levels (`debug`, `info`, `warning`, `error`)
- Removed the `verbose` flag in favor of log levels
- Replaced all `f-strings` with `%` formatting in logging statements to comply with `pylint` requirements
Since `tdqm` directly manages output to the console, mixing its output with standard logging (especially at lower verbosity levels) can lead to overlapping or garbled output.
To addess this, I ensured that:
- The `pbar`(from `tdqm.trange`) is conditionnally displayed depending on the current logging level. When the logging level is set to `INFO` or …

Replace print statements and verbose flag with logging and log levels

---

xdem/coreg/base.py

Resolves #624, see discussion in #621 
New tests will have to be added later separately, because these errors are currently mixed with #584, and #604 is ongoing

Fix inlier masking in BlockwiseCoreg

---

.github/workflows/pip-checks.yml
.github/workflows/python-publish.yml
.github/workflows/python-tests.yml
CONTRIBUTING.md
dev-environment.yml
environment.yml
pyproject.toml
requirements.txt
setup.cfg

And remove CI support for 3.9.

Add support for Python 3.12

---

tests/test_dem.py

To avoid random CI failure in rare cases during the variogram fitting.

Pin random state for `test_estimate_uncertainty`

---

.github/workflows/pip-checks.yml
.github/workflows/python-tests.yml

Their slow "sunsetting" procedure was making CI fail once every 10 days on purpose: https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/.

Deprecate Mambaforge for Miniforge in CI

---

xdem/coreg/workflows.py

Previous method definition triggered a pretty critical `flake8` error in `dem_coregistration`: 
Because the way `coreg = NuthKaab() + VerticalShift()` default argument was defined, it was created during function instantiation (of `dem_coregistration`) and shared across all subsequent use of this function with the default argument, which is not what we want and could have rapidly lead to issues in tests (wrong metadata arguments, such as `fit_called` wrongly starting at `True`, or fixed randomization, etc... because of re-use of the same instance).
The new syntax creates a new instance of `NuthKaab() + VerticalShift()` at every function call.

Fix default method definition in `dem_coregistration`

---

CONTRIBUTING.md
Makefile
README.md
dev-environment.yml
doc/source/how_to_install.md
environment.yml
requirements.txt
setup.cfg

Resolves #582.
This PR introduces the initial Makefile for the `xdem` project, aimed at streamlining the installation process for developers on Linux systems. By implementing a Makefile, we provide a simple command-line interface for common setup tasks, enhancing the developer experience and reducing the potential for errors during installation.
1. **Makefile Structure**: The Makefile has been created based on the existing structure of the `demcompare` project. 
2. **Targets Implemented**:
- **`help`**: Displays help information about available targets.
- **`venv`**: Creates a virtual environment in the specified directory if it does not exist.
- **`install-gdal`**: Installs the version of GDAL corresponding to that of the system.
- **`install`**: Installs the `xdem` package in editable …

Makefile initial installation

---

doc/source/api.md
doc/source/coregistration.md
tests/test_coreg/test_workflows.py
xdem/coreg/workflows.py

Resolves #603.
This PR introduces the ability to specify an initial shift (in X and Y) for DEM co-registration. The key changes include the integration of an `estimated_initial_shift` parameter in the `dem_coregistration()` function, allowing users to apply a custom translation (affine-based) to the source DEM before coregistration.
1. **`dem_coregistration()` function:**
- A new `estimated_initial_shift` parameter is added, allowing users to input a list representing the initial shifts along the X and Y axes.
- If a shift is provided, the source DEM is translated using `geoutils.translate()` based on the calculated pixel resolution.
- The `shift_x` and `shift_y` values in the coregistration method’s metadata (`meta['outputs']['affine']`) are updated to include the initial shifts.
2. …

Add Initial shift Capability to DEM Coregistration

---

.gitignore
doc/source/conf.py
doc/source/coregistration.md
doc/source/uncertainty.md
tests/test_coreg/test_base.py
xdem/coreg/base.py

Partially solves #584.
It looks like the `warp_dem` function was simply in the wrong horizontal direction. This is because the `NuthKaab` metadata used to be the opposite before the homogenization in #530, and it is only tested on that method.
Re-adds `BlockwiseCoreg` to the documentation, with a warning about the functionality being experimental.
This PR does not improve tests (only did visual checking on our example output), this should be done when solving the rest of #584.

Fix `BlockwiseCoreg` shift direction

---

tests/test_spatialstats.py
xdem/spatialstats.py

It was an easy bug fix: moved the subsampling before computing pairwise distances instead of after, which requires using `cdist` instead of `pdist`/`squareform`.
Added new test with large data input, previous ones checking accuracy still passing.
Resolves #590

Reduce RAM usage of `spatial_error_propagation` by optimizing subsampling of pairwise distances

---

tests/test_coreg/test_base.py
xdem/coreg/base.py

Resolves #643.
This pull request introduces a new parameter, `apply_z_correction`, to the `warp_dem` function. This enhancement allows users to control whether vertical correction (Z-offset) is applied during the DEM warping process. The default behavior remains the same, with the Z-correction applied. However, users can now disable this correction by setting `apply_z_correction=False`.
- `apply_z_correction` parameter: A boolean parameter was added to the `warp_dem` function and the `BlockwiseCoreg` class to allow toggling of Z-offset application. When set to False, the Z-adjustment step is skipped during the warping process.
- The test for `warp_dem` has been updated to ensure that the function works as expected when `apply_z_correction=False`.
-  The test also verifies that the …

Add `apply_z_correction` Parameter to `warp_dem` Function

---

.pre-commit-config.yaml
tests/test_coreg/test_base.py
xdem/coreg/base.py

Resolves #604
This PR introduces several bug fixes to the `BlockwiseCoreg` functionnality, focusing on handling missing data and improving robustness in the `stats` method.
In the section of the code where the statistics are collected, for chunks that fail (i.e., where points are not present in `chunk._meta`), the center coordinates are retrieved, and `NaN` values are now stored for the relevant statistics, replacing the absence of values.
Example of the `BlockwiseCoreg.stats()` method output with failing chunks 0 and 1:
| chunk | center_x      | center_y      | center_z   | x_off     | y_off     | z_off     | inlier_count | nmad      | median    |
|-------|---------------|---------------|------------|-----------|-----------|-----------|--------------|-----------|-----------|
| 0     | …

Implement Nan padding in blockwise coregistration stats

---

tests/test_coreg/test_biascorr.py

Resolves #677 
Silences the optimize covariance warning for `test_biascorr__bin_and_fit_2d` as it was done in other functions.
Adds more points to the binning in `test_biascorr__bin_and_fit_1d` to avoid the optimize error.

Fix SciPy warnings and errors

---

.gitignore
Makefile
dev-environment.yml
setup.cfg
tests/conftest.py
tests/test_coreg/test_affine.py
tests/test_terrain.py
xdem/examples.py

Resolves #671.
The purpose of this PR is to eliminate dependencies on `GDAL` and `RichDEM` in the `xDEM` tests, thereby simplifying the installation process for developers. The scripts related to `GDAL` and `RichDEM` have been relocated to the xdem-data repository, where they generate and save the ground truth data in `.tif` format. These `.tif` files are then imported into xDEM during test execution.
- The functions related to `GDAL` and `RichDEM` have been removed from `conftest.py` and the test files, and transferred to `xdem-data`. These functions have been replaced by calls to the ground truths generated within `xdem-data`.
- New functions have been added to `conftest.py` and functions in `examples.py` has been modified to retrieve the ground truth data from the xdem-data repository. …

Remove GDAL and RichDEM dependancy from tests

---

tests/test_coreg/test_affine.py
xdem/coreg/affine.py
xdem/coreg/base.py

Resolves #686.
This PR introduces a new feature to the Nuth and Kääb (2011) coregistration method, allowing users to optionally disable the vertical shift during the coregistration process. A new boolean parameter `apply_vertical_shift` has been added to control whether the vertical translation (shift in the z-axis) should be applied.
- Added `apply_vertical_shift` to the constructor of the NuthKaab class, defaulting to True to maintain the current behavior (vertical shift enabled by default).
- Modified method `_nuth_kaab_iteration_step` to conditionally apply the vertical shift based on the value of `apply_vertical_shift`.
If the parameter is not provided, the default behavior (applying the vertical shift) remains unchanged, ensuring no impact on existing usage.
```python
coreg_method = …
```

Add Option to Disable Vertical Shift in Nuth and Kääb Coregistration

---

AUTHORS.md
CODE-OF-CONDUCT.md
GOVERNANCE.md
doc/source/authors.md

Now that CNES and GlacioHack are working together to maintain xDEM, it is necessary to propose a governance model to ensure that the current collaboration continues smoothly, and if possible, to increase the number of contributors who would feel reassured with the establishment of a structured working framework.
To this end, we have added two files: one for governance and one for the code of conduct.
These files are inspired by the MVG (Minimum Viable Governance) project [https://github.com/github/mvg](https://github.com/github/mvg) and [https://www.contributor-covenant.org/](https://www.contributor-covenant.org/).
We can use this PR to discuss any changes that need to be made.

Add Governance and code of conduct files

---

dev-environment.yml
doc/source/dem_class.md
environment.yml
requirements.txt
xdem/dem.py

Resolves #602.
Completes GlacioHack/geoutils#642.
Completes GlacioHack/geoutils#638.
This PR introduces the ability to use a Region of Interest (ROI) when working with `xdem.DEM`, which is a subclass of `geoutils.Raster`. This functionality allows users to focus on specific regions within the raster data without having to load or process the entire dataset.
- A section about statistics has been added to the `DEM` class documentation.
- A section about the ROI has been added to the `DEM` class documentation.
1. Statistics:
- Get all statistics in a dict:
```{code-cell} ipython3
dem.get_stats()
```
- Get a single statistic (e.g., 'mean') as a float:
```{code-cell} ipython3
dem.get_stats("mean")
```
- Get multiple statistics in a dict:
```{code-cell} ipython3
dem.get_stats(["mean", "max", …
```

Update documentation for ROI and stats

---

AUTHORS.md
tests/test_filters.py
xdem/filters.py

This PR adds to the available filters minimum, maximum, median and mean filters useful for the CNES QI team. 
Each filter's function has a 2D/3D input array (`array`) and the size of the kernel (`kernel_size`) as parameters. We get the filtered array in output, with the same shape as the input array. The filters are robust to NaN values.
These additions are temporary in xDEM and will be moved to GeoUtils in the future.
- New functions added into `filters.py` :
- `median_filter_scipy()` for scipy median filter
- `median_filter()` for mean filter
- `min_filter_scipy()` for scipy minimum filter
- `max_filter_scipy()` for scipy maximum filter
- Tests added into `test_filters.py` :
- `test_median_filter()`
- `test_mean_filter()`
- `test_min_filter()`
- `test_max_filter()`

Add min, max, mean and median filters

---

.pre-commit-config.yaml
dev-environment.yml
environment.yml
requirements.txt
tests/test_terrain.py
tests/test_volume.py
xdem/_typing.py
xdem/terrain.py
xdem/volume.py

This PR updates xDEM to support NumPy 2.0.
Follows the same update in GeoUtils: https://github.com/GlacioHack/geoutils/pull/605. And also requires a default nodata defined for int64 types: https://github.com/GlacioHack/geoutils/pull/680.
Two main changes:
1. As NumPy 2.0 now returns typed scalars (e.g., `np.float32(1.0)` instead of `1.0`), it made doctests fail in `terrain.py`. This was the occasion to also catch that attributes had inconsistent output data types (sometimes `np.float32`, sometimes `np.float64`).
As a fix, a new `out_dtype` argument can be passed to `get_terrain_attibute` to define which data type should have the output during calculation, which defaults to the `dtype` of the input DEM. All Numba-optimized functions now have arrays initialized on those data types, which …

Add NumPy 2 support

---

examples/advanced/plot_blockwise_coreg.py
examples/advanced/plot_deramp.py
examples/advanced/plot_heterosc_estimation_modelling.py
examples/advanced/plot_norm_regional_hypso.py
examples/advanced/plot_standardization.py
examples/advanced/plot_variogram_estimation_modelling.py
examples/basic/plot_nuth_kaab.py
tests/test_coreg/test_blockwise.py
tests/test_coreg/test_workflows.py
tests/test_spatialstats.py
xdem/coreg/affine.py
xdem/coreg/base.py
xdem/coreg/workflows.py
xdem/dem.py
xdem/spatialstats.py
xdem/terrain.py

Resolves #715.
- Deletes `spatialstats.nmad`.
- Switches `xdem.spatialstats.nmad` to `geoutils.stats.nmad`.
- Needs GlacioHack/geoutils#678

Switch the `nmad` of xDEM to the `nmad` of GeoUtils

---

.github/workflows/pip-checks.yml
NOTICE
dev-environment.yml
doc/source/coregistration.md
environment.yml
examples/advanced/plot_blockwise_coreg.py
requirements.txt
tests/test_coreg/test_base.py
tests/test_coreg/test_blockwise.py
xdem/coreg/blockwise.py

Lots of work to do but we will use this PR to debate tomorrow

Refactor blockwise coregistration method

---

.github/workflows/pip-checks.yml
NOTICE
dev-environment.yml
environment.yml
requirements.txt
tests/test_coreg/test_blockwise.py
xdem/coreg/blockwise.py

This PR includes the change from pyransac3d to the sklearn.linear\_model module.
We have removed all calls to and references to pyransac3d.
We have refactored the ransac function, which now appears less non-deterministic than before.
We have updated the unit tests.

Use sklearn instead of pyransac3d

---

tests/test_dem.py
xdem/dem.py

Replaces #740 
This is an easier fix than #740: Simply an `if` statement depending on the output of `Raster.from_array`. 
Another way to do this for a future re-work (if we want users to more easily subclass `Raster`, for example) would be to separate `Raster.from_array()` into a non-public function that does the casting under-the-hood for all arithmetic ops (`Raster._from_array()`, which wouldn't be overloaded by `DEM.from_array()`) and a public function that works only for building a Raster as intended (refuses a `boolean` input).
Actually, we might have to already do this for the Xarray accessors, for consistency in the behaviour.
Resolves #739

Fix `DEM` casting to `Mask` by removing `from_array` overloading

---

dev-environment.yml
environment.yml
requirements.txt
xdem/spatialstats.py

The dependency was primarily used in the old `warp_dem` that's been deprecated in #707. We don't need it anymore.
Resolves #654

Remove SciKit-Image dependency

---

pyproject.toml

Currently, the CI is failing to find the xdem installations. This is due to a recent release of [setuptools_scm](https://github.com/pypa/setuptools-scm/releases/tag/v9.2.0) : 
While waiting for a 100% python CI without conda to be implemented, I suggest pinning the version of setuptools.
EDIT from @rhugonnet: See issue here: https://github.com/pypa/setuptools-scm/issues/1213

Pin setuptools_scm max version to `9.0` to avoid build failures

---

.pre-commit-config.yaml
dev-environment.yml

This PR fixes the setup of Mypy which was breaking locally due to the NumPy plugin (and soon in CI), by pinning NumPy 2.0.X.
This PR also adds `pre-commit` to `dev-environment.yml` to have it already setup after a dev install.
We'll have to remove the NumPy plugin in time due to deprecation, see #782.
But this involves updating to NumPy 2.3.X, which triggers many more static typing checks, so let's do this in a PR updating most of the static typing.

Fix setup of MyPy temporarily and add `pre-commit` to dev-environment
